# Generated by Django 3.1.3 on 2020-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_inputdata_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
