# Generated by Django 3.1.3 on 2020-11-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20201107_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
